# Generated by Django 3.2.13 on 2022-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20220414_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
