# Generated by Django 3.2.13 on 2022-04-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_adresse_country'),
        ('archives', '0010_auto_20220423_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.trip'),
        ),
    ]
