# Generated by Django 3.2.13 on 2022-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_auto_20220513_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
