# Generated by Django 3.2.13 on 2022-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_character_gender'),
        ('archives', '0014_newspaper_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='founder',
            field=models.ManyToManyField(to='profiles.Character'),
        ),
    ]
