# Generated by Django 3.2.13 on 2022-05-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='transcription',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.newspaper'),
        ),
    ]
