# Generated by Django 3.2.13 on 2022-05-14 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0017_auto_20220513_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.fond'),
        ),
    ]
