# Generated by Django 3.2.13 on 2022-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0019_auto_20220514_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='date_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='date_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
