# Generated by Django 3.2.13 on 2022-05-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0020_auto_20220514_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.depot'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.country'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fond',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.depot'),
        ),
    ]
