# Generated by Django 3.2.13 on 2022-05-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0021_auto_20220515_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='depot',
        ),
    ]
