# Generated by Django 3.2.13 on 2022-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0022_remove_document_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='event',
        ),
    ]
