# Generated by Django 3.2.13 on 2022-04-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='experience',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.character'),
        ),
    ]
