# Generated by Django 3.2.13 on 2022-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220415_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Compagnies'},
        ),
    ]
