# Generated by Django 3.2.13 on 2022-04-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='character',
            name='date_death',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
