# Generated by Django 3.2.13 on 2022-04-19 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220419_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_death',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
