# Generated by Django 3.2.13 on 2022-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('masculin', models.CharField(max_length=100)),
                ('feminin', models.CharField(max_length=100)),
            ],
        ),
    ]
