# Generated by Django 3.2.13 on 2022-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_auto_20220523_1051'),
        ('profiles', '0013_placemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemanagement',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.place'),
        ),
    ]
