# Generated by Django 3.2.13 on 2022-05-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_placemanagement_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemanagement',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.transmission'),
        ),
    ]
