# Generated by Django 3.2.13 on 2022-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_placemanagement_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='notaire',
            field=models.ManyToManyField(to='profiles.Character'),
        ),
    ]
