# Generated by Django 3.2.13 on 2022-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20220531_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='heraldry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
