# Generated by Django 3.2.13 on 2022-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_fonction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='gender',
            field=models.CharField(blank=True, choices=[('pluriel', 'pluriel'), ('féminin', 'féminin'), ('masculin', 'masculin'), ('voyelle', 'voyelle')], max_length=30, null=True),
        ),
    ]
