# Generated by Django 3.2.13 on 2022-06-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20220602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'Male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkfather', to='profiles.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'Female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkmother', to='profiles.character'),
        ),
    ]
