# Generated by Django 3.2.13 on 2022-06-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20220602_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
