# Generated by Django 3.2.13 on 2022-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_activity_paid'),
        ('profiles', '0023_auto_20220602_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='acheteur',
            field=models.ManyToManyField(related_name='linkacheteur', to='profiles.Character'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='place',
            field=models.ManyToManyField(to='travel.Place'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='vendeur',
            field=models.ManyToManyField(related_name='linkvendeur', to='profiles.Character'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='notaire',
            field=models.ManyToManyField(related_name='linknotaire', to='profiles.Character'),
        ),
        migrations.DeleteModel(
            name='PlaceManagement',
        ),
    ]
