# Generated by Django 3.2.13 on 2022-04-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220415_0119'),
        ('archives', '0006_auto_20220414_1255'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.country'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('traveller', models.ManyToManyField(to='profiles.Character')),
            ],
        ),
    ]
