# Generated by Django 3.2.13 on 2022-04-15 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20220415_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
