# Generated by Django 3.2.13 on 2022-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20220415_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
