# Generated by Django 3.2.13 on 2022-04-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
