# Generated by Django 3.2.13 on 2022-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_rename_addresse_activity_adresse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
