# Generated by Django 3.2.13 on 2022-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('Hébergement', 'Hébergement'), ('RESTAURATION', 'Restauration'), ('LOISIR', 'Loisir')], max_length=30, verbose_name='catégorie'),
        ),
    ]
