# Generated by Django 3.2.13 on 2022-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('Hébergement', 'Hébergement'), ('RESTAURATION', 'Restauration'), ('LOISIR', 'Loisir')], max_length=30),
        ),
    ]
