# Generated by Django 3.2.13 on 2022-04-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Hébergement', 'Hébergement'), ('Restauration', 'Restauration'), ('Loisir', 'Loisir')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.trip'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
