# Generated by Django 3.2.13 on 2022-04-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_country_options'),
        ('travel', '0010_auto_20220422_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.country'),
        ),
    ]
