# Generated by Django 3.2.13 on 2022-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_adresse_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
