# Generated by Django 3.2.13 on 2022-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_adresse_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='libelle',
        ),
        migrations.AddField(
            model_name='adresse',
            name='place',
            field=models.ManyToManyField(to='travel.Place'),
        ),
    ]
