# Generated by Django 3.2.13 on 2022-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20220516_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='adresse',
            field=models.ManyToManyField(to='travel.Adresse'),
        ),
    ]
