# Generated by Django 3.2.13 on 2022-05-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_place_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='adresse',
        ),
        migrations.AddField(
            model_name='place',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.adresse'),
        ),
    ]
