# Generated by Django 3.2.13 on 2022-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20220518_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placecategory',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
