# Generated by Django 3.2.13 on 2022-05-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_auto_20220518_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.place'),
        ),
    ]
