# Generated by Django 3.2.13 on 2022-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_event'),
        ('travel', '0021_alter_activity_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visitor',
            field=models.ManyToManyField(to='profiles.Character'),
        ),
    ]
