# Generated by Django 3.2.13 on 2022-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_event'),
        ('travel', '0022_place_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visitor',
        ),
        migrations.AddField(
            model_name='activity',
            name='visitor',
            field=models.ManyToManyField(to='profiles.Character'),
        ),
    ]
