# Generated by Django 3.2.13 on 2022-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_auto_20220518_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
