# Generated by Django 3.2.13 on 2022-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_alter_adresse_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
