# Generated by Django 3.2.13 on 2022-05-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_auto_20220523_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='adresse',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
