# Generated by Django 3.2.13 on 2022-05-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_auto_20220530_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.city'),
        ),
    ]
