# Generated by Django 3.2.13 on 2022-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_adresse_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
