# Generated by Django 3.2.13 on 2022-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_auto_20220530_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
