# Generated by Django 3.2.13 on 2022-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='caption',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tag'),
        ),
    ]
