# Generated by Django 3.2.13 on 2022-04-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0002_alter_db_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='caption',
            new_name='tag',
        ),
    ]
