# Generated by Django 3.2.13 on 2022-04-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_rename_caption_db_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Fichier'),
        ),
    ]
