# Generated by Django 3.2.13 on 2022-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0004_alter_db_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db',
            name='tag',
        ),
        migrations.AddField(
            model_name='db',
            name='software',
            field=models.CharField(blank=True, choices=[('HEREDIS', 'Heredis'), ('CALIBRE', 'Calibre')], max_length=30, null=True, verbose_name='logiciel'),
        ),
        migrations.AlterField(
            model_name='db',
            name='file',
            field=models.FileField(upload_to='', verbose_name='fichier'),
        ),
    ]
