# Generated by Django 3.2.13 on 2022-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0005_auto_20220414_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='software',
            field=models.CharField(choices=[('HEREDIS', 'Heredis'), ('CALIBRE', 'Calibre')], max_length=30, verbose_name='logiciel'),
        ),
    ]
