# Generated by Django 3.2.13 on 2022-06-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookPost',
        ),
        migrations.DeleteModel(
            name='InstagramPost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='TwitterPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
