# Generated by Django 3.2.13 on 2022-06-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0003_auto_20220602_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='WordNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_id', models.PositiveIntegerField()),
                ('noun_ct', models.ForeignKey(limit_choices_to={'model__in': ('EnNoun', 'FrNoun')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.word')),
            ],
        ),
        migrations.CreateModel(
            name='FrNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.word')),
            ],
        ),
        migrations.CreateModel(
            name='EnNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.word')),
            ],
        ),
    ]
