# Generated by Django 3.2.13 on 2022-06-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_ennoun_frnoun_word_wordnoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='ennoun',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ennoun',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.word'),
        ),
        migrations.AlterField(
            model_name='frnoun',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frnoun',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.word'),
        ),
    ]
